let shopItemsData = [
  {
    id: "ioytrhndcv",
      name: "Ravenclaw Robe",
      price: 100,
      desc: "Winters came early? we got you covered wij's scarf",
      img: "cho-1.jpg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Slythrin Scarf",
      price: 350,
      desc: "Winters came early? we got you covered with house Slytherin's scarf",
      img: "scarf-hufflepuff.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "Time Turner",
      price: 25,
      desc: "Going back to the last day just made easy as breathn=",
      img: "time-turner.png",
    },
    {
      id: "thyfhcbcv",
      name: "Marauder's Map",
      price: 249,
      desc: "You'll know what you're buying to see people walk",
      img: "map.png",
    },
    {
      id: "jfhgbvnscs",
      name: "Nimbus 2001",
      price: 45,
      desc: "Bro so fast it reached to the first even in the list of products",
      img: "nimbus-2001.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Slytherin Scarf",
      price: 350,
      desc: "Winters came early? we got you covered with house Slytherin's Scarf",
      img: "scarf-slytherin.png",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Hufflepuff Robe",
      price: 1066,
      desc: "Robe of the Hufflepuff house of the Hogwart's school of  witchcraft and wisardry",
      img: "cedric-1.jpg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Deathly Hallows Necklace",
      price: 249,
      desc: "three who are strong together make you strong as well",
      img: "trinity.png",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Triwizard Cup",
      price: 599,
      desc: "Not everyone can win the Triwizard cup but, can have this cup!",
      img: "Triwizard_Cup.webp",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Gryffindor Robe",
      price: 1599,
      desc: "Who doesn't want to be a part of the most decorated house? Get it now!!",
      img: "hermione-1.jpg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Slytherin Sweater",
      price: 899,
      desc: "Winters came early? we got you covered with house Slytherin's Sweater",
      img: "sweater-slytherin.png",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Ravenclaw's Lost Diadem",
      price: 999,
      desc: "Is this a lost item? Well not anymore 'cause we got it here exclusively!",
      img: "diadem.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Hufflepuff Sweater",
      price: 799,
      desc: "Winters came early? we got you covered with house Ravenclaw's Sweater",
      img: "sweater-hufflepuff.png",
    },
    {
      id: "oiopijmjkhuihb",
      name: "Slytherin Robe",
      price: 1299,
      desc: "Feel yourself as a part of the strongest house of all!",
      img: "draco-2.jpg",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Ravenclaw Scarf",
      price: 349,
      desc: "Winters came early? we got you covered with house Ravenclaw's scarf",
      img: "scarf-ravenclaw.webp",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Horcrux Necklace",
      price: 149,
      desc: "Looks nice, doesn't it? Get your hand on one of these!",
      img: "horcrux.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Ravenclaw Sweater",
      price: 799,
      desc: "Winters came early? we got you covered with house Ravenclaw's Sweater",
      img: "sweater-ravenclaw.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Sorting Hat",
      price: 349,
      desc: "This one doesn't do the talking but its design sure does!",
      img: "hat.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Gryffindor Scarf",
      price: 499,
      desc: "Winters came early? we got you covered with house gryffindor's scarf",
      img: "scarf-gryffindor.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Elder Wand",
      price: 3699,
      desc: "Well, a wand with such design and a Thestral hair core isnt seen everyday!",
      img: "elder-wand.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Custom Hogwarts' letters",
      price: 149,
      desc: "Not a hogwarts student? These customised letters are curated for you!.",
      img: "letters.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Luna Lovegood's glasses",
      price: 99,
      desc: "Wear these to observe what others don't even see!",
      img: "luna-glasses.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Harry's Wand",
      price: 3699,
      desc: "Embedded with the core of a Phoenix feather, this wand is one among the strongest!",
      img: "harry-wand.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Gryffindor's Sword",
      price: 749,
      desc: "Are you worthy enough to get your hands on the holy sword?",
      img: "sword.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Horcrux Ring",
      price: 249,
      desc: "Cursed for some, blessed for others...",
      img: "ring.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Nimbus 2000",
      price: 1699,
      desc: "The best in the business and you can take my word for it!",
      img: "nimbus-2000.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Messenger Owl",
      price: 2449,
      desc: "When you live away from your family, an owl is the partner you need!",
      img: "owl.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Quidditch Set",
      price: 799,
      desc: "What could be better to start school with a full quidditch set!!",
      img: "quidditch-set.jpeg",
    },
 ];