
// app.use(express.static(path.join(__dirname,'photos')))
let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Nimbus 2001",
    price: 2899,
    desc: "Bro so fast, it reached to the first even in the list of products",
    img: "/photos/nimbus-2001.png",
  },
  {
  id: "ioytrhndcv",
    name: "Ravenclaw Robe",
    price: 1099,
    desc: "Winters came early? we got you covered with house Ravenclaw's scarf",
    img: "/photos/cho-1.jpg",
  },
  {
    id: "rtytytuyuytyytbvnASDF",
    name: "Hufflepuff Scarf",
    price: 349,
    desc: "Winters came early? we got you covered with house Slytherin's scarf",
    img: "/photos/scarf-hufflepuff.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Time Turner",
    price: 2399,
    desc: "Is this just a locket or something else? Get it now to find out!",
    img: "/photos/time-turner.png",
  },
  {
    id: "thyfhcbcv",
    name: "Marauder's Map",
    price: 1799,
    desc: "You'll know what you're buying to see people walk",
    img: "/photos/map.png",
  },
  {
    id: "rtytytuyuytyytbSFAS",
    name: "Slytherin Scarf",
    price: 449,
    desc: "Winters came early? we got you covered with house Slytherin's Scarf",
    img: "/photos/scarf-slytherin.png",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Hufflepuff Robe",
    price: 1066,
    desc: "Robe of the Hufflepuff house of the Hogwart's school of  witchcraft and wisardry",
    img: "/photos/cedric-1.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Deathly Hallows Necklace",
    price: 249,
    desc: "three who are strong together make you strong as well",
    img: "/photos/trinity.png",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Triwizard Cup",
    price: 599,
    desc: "Not everyone can win the Triwizard cup but, can have this cup!",
    img: "/photos/Triwizard_Cup.webp",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Gryffindor Robe",
    price: 1599,
    desc: "Who doesn't want to be a part of the most decorated house? Become a part now!!",
    img: "/photos/hermione-1.jpg",
  },
  {
    id: "rtytytuyuytyytbvASDFncv",
    name: "Slytherin Sweater",
    price: 899,
    desc: "Winters came early? we got you covered with house Slytherin's Sweater",
    img: "/photos/sweater-slytherin.png",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Ravenclaw's Lost Diadem",
    price: 999,
    desc: "Is this a lost item? Well not anymore 'cause we got it here exclusively!",
    img: "/photos/diadem.png",
  },
  {
    id: "rtytytuyuyasdftyyasdftbvncv",
    name: "Hufflepuff Sweater",
    price: 799,
    desc: "Winters came early? we got you covered with house Hufflepuff's Sweater",
    img: "/photos/sweater-hufflepuff.png",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Slytherin Robe",
    price: 1299,
    desc: "Feel yourself as a part of the strongest house of all!",
    img: "/photos/draco-2.jpg",
  },
  {
    id: "rtytytuyuwqrytyytbvncv",
    name: "Ravenclaw Scarf",
    price: 349,
    desc: "Winters came early? we got you covered with house Ravenclaw's scarf",
    img: "/photos/scarf-ravenclaw.webp",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Horcrux Necklace",
    price: 149,
    desc: "Looks nice, doesn't it? Get your hand on one of these!",
    img: "/photos/horcrux.png",
  },
  {
    id: "rtytytucxyuytyytbvncv",
    name: "Ravenclaw Sweater",
    price: 799,
    desc: "Winters came early? we got you covered with house Ravenclaw's Sweater",
    img: "/photos/sweater-ravenclaw.png",
  },
  {
    id: "rtytytuyuaytyytbvncv",
    name: "Sorting Hat",
    price: 349,
    desc: "This one doesn't do the talking but its design sure does!",
    img: "/photos/hat.png",
  },
  {
    id: "rtytytuyuyftyytbvncv",
    name: "Gryffindor Scarf",
    price: 499,
    desc: "Winters came early? we got you covered with house gryffindor's scarf",
    img: "/photos/scarf-gryffindor.png",
  },
  {
    id: "rdtytytuyuytyytbvncv",
    name: "Elder Wand",
    price: 3699,
    desc: "Well, a wand with such design and a Thestral hair core isnt seen everyday!",
    img: "/photos/elder-wand.png",
  },
  {
    id: "rtytytuyuytgyytbvncv",
    name: "Custom Hogwarts' letters",
    price: 149,
    desc: "Not a hogwarts student? These customised letters are curated for you!.",
    img: "/photos/letters.png",
  },
  {
    id: "rtytytuyuyvtyytbvncv",
    name: "Luna Lovegood's glasses",
    price: 499,
    desc: "Wear these to observe what others don't even see!",
    img: "/photos/luna-glasses.png",
  },
  {
    id: "rtytytuyuyxtyytbvncv",
    name: "Harry's Wand",
    price: 3699,
    desc: "Embedded with the core of a Phoenix feather, this wand is one among the strongest!",
    img: "/photos/harry-wand.png",
  },
  {
    id: "rtytytuyuaytyytbvncv",
    name: "Gryffindor's Sword",
    price: 749,
    desc: "Are you worthy enough to get your hands on the holy sword?",
    img: "/photos/sword.png",
  },
  {
    id: "rtytytuyuytdyytbvncv",
    name: "Horcrux Ring",
    price: 249,
    desc: "Cursed for some, blessed for others...",
    img: "/photos/ring.png",
  },
  {
    id: "rtytytuywuytyytbvncv",
    name: "Nimbus 2000",
    price: 2799,
    desc: "The best in the business and you can take my word for it!",
    img: "/photos/nimbus-2000.png",
  },
  {
    id: "rtytytuyfuytyytbvncv",
    name: "Messenger Owl",
    price: 2449,
    desc: "When you live away from your family, an owl is the partner you need!",
    img: "/photos/owl.png",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Quidditch Set",
    price: 799,
    desc: "What could be better to start school with a full quidditch set!!",
    img: "/photos/quidditch-set.jpeg",
  },
 ];